spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root